[package]
authors = ["Richard Cook"]
categories = ["encoding", "filesystem"]
description = "Jack of All Trades Master of None"
edition = "2021"
homepage = "https://github.com/rcook/joatmon-rs"
keywords = ["general"]
license = "MIT"
name = "joatmon"
repository = "https://github.com/rcook/joatmon-rs"
version = "0.0.28"

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
toml = "0.7.4"
toml_edit = "0.19.10"

[dev-dependencies]
serial_test = "2.0.0"
rstest = "0.17.0"
tempdir = "0.3.7"
