[package]
authors = ["Richard Cook"]
description = "Jack of All Trades Master of None"
homepage = "https://github.com/rcook/joatmon-rs/"
license = "MIT"
name = "joatmon"
version = "0.0.26"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
toml = "0.7.3"
toml_edit = "0.19.8"

[dev-dependencies]
serial_test = "2.0.0"
rstest = "0.17.0"
tempdir = "0.3.7"
