name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 5 * * *

jobs:
  ci:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
        include:
          - target: x86_64-apple-darwin
            host_os: macos-latest
    runs-on: ${{ matrix.host_os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run tests
        shell: bash
        run: cargo test -- --show-output
