name: CI

env:
  project: joatmon

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 5 * * *

jobs:
  ci:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
        include:
          - target: x86_64-apple-darwin
            host_os: macos-latest
          - target: x86_64-pc-windows-msvc
            host_os: windows-latest
          - target: x86_64-unknown-linux-gnu
            host_os: ubuntu-latest
    runs-on: ${{ matrix.host_os }}
    env:
      cargo: cargo
      CARGO_TERM_COLOR: always
    steps:
      - name: Set variables
        shell: bash
        run: echo "target_flags=--target ${{ matrix.target }}" >> $GITHUB_ENV

      - name: Check out
        uses: actions/checkout@v3

      - name: Build (debug)
        run: ${{ env.cargo }} build --verbose ${{ env.target_flags }}

      - name: Run tests (debug)
        run: ${{ env.cargo }} test --verbose ${{ env.target_flags }}

      - name: Build (release)
        run: ${{ env.cargo }} build --verbose --release ${{ env.target_flags }}

      - name: Run tests (release)
        run: ${{ env.cargo }} test --verbose --release ${{ env.target_flags }}

      - name: Run Clippy
        run: ${{ env.cargo }} clippy ${{ env.target_flags }}

      - name: Run fmt
        run: ${{ env.cargo }} fmt --check
