name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build, test and publish Rust package
        uses: rcook/rust-package-action@v0.0.2
        with:
          target: x86_64-unknown-linux-gnu
          publish: true
        env:
          RUST_PACKAGE_ACTION_CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
