name: Publish

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  publish:
    name: Publish to crates.io
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      steps:
        - name: Check out
          uses: actions/checkout@v3

      - shell: bash
        run: |
          cargo publish --token ${{ env.JOATMON_RS_CRATES_IO_API_TOKEN }}
        env:
          JOATMON_RS_CRATES_IO_API_TOKEN: ${{ secrets.JOATMON_RS_CRATES_IO_API_TOKEN }}
