name: Publish

on:
  push:
    tags:
      - v*.*.*

#on:
#  workflow_run:
#    workflows:
#      - Release
#    types:
#      - completed

jobs:
  publish:
    name: Publish to crates.io
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cargo publish
        shell: bash
        run: |
          cargo publish --token ${{ env.JOATMON_RS_CRATES_IO_API_TOKEN }} --target x86_64-unknown-linux-musl
        env:
          JOATMON_RS_CRATES_IO_API_TOKEN: ${{ secrets.JOATMON_RS_CRATES_IO_API_TOKEN }}
